server:
  port: 8082
  undertow:
    ioThreads: 15
    workerThreads: 150
    accesslog:
      enabled: true
  compression:
    enabled: true
    mimeTypes: application/json, text/xml
    minResponseSize: 4096

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: r00tR))T

    
  application:
    name: BorrowerMS